alitto/pond

- .travis.yml
- examples/dynamic_size/go.mod
- examples/fixed_size/go.mod
- examples/prometheus/go.mod
- examples/task_group/go.mod
- go.mod
- pond.go
- Prevent `waitingTasks` counter to wrap around (https://github.com/alitto/pond/issues/12)
- Upgrade go to v1.16
> Prevent WaitingTasks counter to wrap around and upgrade to Go v1.16

- pond.go
- pond_test.go
- Prevent panic thrown in purger goroutine when attempting to stop a worker after `tasks` channel is closed (reported in https://github.com/alitto/pond/pull/26). The change consists on avoiding closing the `tasks` channel in the first place. Go literature recommends [not closing channels](https://go101.org/article/channel-closing.html) that are written to by multiple sender goroutines:
> One general principle of using Go channels is don't close a channel from the receiver side and don't close a channel if the channel has multiple concurrent senders.
- Ensure calls to `StopAndWait()` from multiple goroutines concurrently makes them all wait until all tasks have completed.
> Prevent "send on closed channel" panic in purger goroutine

- benchmark/go.mod
- examples/dynamic_size/go.mod
- examples/fixed_size/go.mod
- examples/pool_context/go.mod
- examples/prometheus/go.mod
- examples/task_group/go.mod
- pond.go
- pond_blackbox_test.go
- pond_test.go
- resizer.go
- Allow concurrent calls to StopAndWait
- Restore semantics of `Stop` method, which shouldn't wait for queued tasks to complete before killing worker goroutines
- Simplify logic in submit function
- Prevent `hits` counter in RatedResizer from going to negative values
- Add more tests
> Allow concurrent calls to StopAndWait

- .github/workflows/main.yml
- README.md
- examples/dynamic_size/go.mod
- examples/fixed_size/go.mod
- examples/group_context/go.mod
- examples/group_context/group_context.go
- examples/pool_context/go.mod
- examples/task_group/go.mod
- go.mod
- group.go
- group_blackbox_test.go
- pond.go
- pond_blackbox_test.go
- Upgrade go version to 1.8
- Implement new method in WorkerPool to create a group of tasks associated to a context `GroupContext(ctx context.Context)`
- Move `TaskGroup` to a separate file
- Move tests related to task groups to a separate file
> Implement task group associated to a Context & more

- .github/workflows/main.yml
- Makefile
- examples/dynamic_size/go.mod
- examples/fixed_size/go.mod
- examples/group_context/go.mod
- examples/pool_context/go.mod
- examples/prometheus/go.mod
- examples/task_group/go.mod
- go.mod
- pond.go
- pond_test.go
- worker.go
- Fix for https://github.com/alitto/pond/issues/33
- Upgrade to go 1.19
- Extracted counter updates from main `worker` function to make it simpler and more generic
- Moved `worker` function to a separate file
- Added `Makefile` with test targets
> Prevent deadlock when purging idle worker during task submission

- group.go
That is not stated whether `Wait()` & `Submit()` for `TaskGroupWithContext` are allowed for usage from different execution threads. As end user I expected that it is.
```golang
// thread 1
group.Submit(func() error {
return errors.New("failed")
})
// thread 2
group.Wait()
```
leads to race condition because of non-synchronized ([write](https://github.com/alitto/pond/blob/c7a74b9be5dd41f8f529f249b5655adae31231cf/group.go#L61) & [read](https://github.com/alitto/pond/blob/c7a74b9be5dd41f8f529f249b5655adae31231cf/group.go#L89)) operations to `.err`.
The problem is detectable in 100% cases by a built-in race checker.
The change introduces usage of mutex to synchronize access to this variable at the above mentioned code flows.
> Synchronize read & write of `TaskGroupWithContext`'s `err` variable

- .github/workflows/main.yml
- group.go
- group_blackbox_test.go
- As pointed out by @NOMORECOFFEE in https://github.com/alitto/pond/pull/37#pullrequestreview-1163451413, make sure Context's error is returned by `Wait()` when it's completed (canceled/timed out) before at least 1 task returned an non-nil error.
- Upgrade codecov-action to v3 https://github.com/codecov/codecov-action
> Return Context error if it is canceled before at least 1 task failed

- README.md
😅 **The code does not align with the text。**
----
> docs: format doc

- .github/workflows/main.yml
- examples/dynamic_size/go.mod
- examples/fixed_size/go.mod
- examples/group_context/go.mod
- examples/pool_context/go.mod
- examples/prometheus/go.mod
- examples/task_group/go.mod
- go.mod
- Updated list of go versions used in github actions workflow
- Bumped module's go version to `1.21` (when selecting `1.22` github actions crash with an error)
> chore(workflows): update go version and tested versions in github actions workflow

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- examples/dynamic_size/go.mod
- examples/fixed_size/go.mod
- examples/group_context/go.mod
- examples/pool_context/go.mod
- examples/prometheus/go.mod
- examples/task_group/go.mod
- go.mod
- Bump max supported go version to 1.22
- Correct go version specified in `go.mod` to reflect the minimum version of the Go compiler that is supported by the source code
- Upgrade versions of actions in Github Actions workflows
> chore(go): bump max supported go version to 1.22

- pond.go
- pond_blackbox_test.go
> Return context in Stop() to notify user when everything has been stopped

- worker.go
I think we also need to return immediately in the inner `context.Done()`, otherwise it is possible to loop all the time. According to https://stackoverflow.com/a/51296312, it also returns immediately.
> Fix bug that worker doesn't return after context cancel

- pond.go
- pond_blackbox_test.go
- worker.go
Fix [Issue #70](https://github.com/alitto/pond/issues/70)
> Drain tasks in an unblocked way to avoid data race

- README.md
- group.go
- group_test.go
- internal/future/composite.go
- Skip remaining tasks in a task group after its context is cancelled
- Improve documentation around usage of `context.Context`
> fix(taskgroups): do not start remaining tasks after context cancellation

- Makefile
- group.go
- group_test.go
- internal/dispatcher/dispatcher_test.go
- internal/future/composite.go
- internal/future/composite_test.go
- result.go
This pull request includes multiple changes to improve the task group functionalities and their associated tests in the `pond` package. The most important changes include updating the `Wait` method behavior, adding context support to task groups, and enhancing test cases to cover new scenarios.
* Allow running tasks to complete if a group is stopped or its context is cancelled.
* Return result values of tasks that have completed instead of an empty slice when a group is stopped, its context is cancelled or one of the tasks returns an error.
* Added detailed comments to the `Wait` methods in `TaskGroup` and `ResultTaskGroup` interfaces to clarify the behavior when tasks return errors, the context is canceled, or the group is stopped.
* Added `NewGroupContext` method to `ResultPool` to …
> feat(taskgroup): wait for ongoing tasks complete when group is stopped or context is cancelled

- group.go
- group_test.go
This pull request includes changes to the `group.go` file to improve task submission handling and adds new test cases to ensure the functionality of task group metrics and handling of cancelled contexts.
* Changed the `submit` function to use `g.pool.dispatcher.Write` for task execution, which returns an error if the context is cancelled or an error occurs during task invocation. (`group.go`, [group.goL107-R115](diffhunk://#diff-996f64128c7fffe6cc8254ea4e1ac3c5693956f86ab5c8952e525083cf14ca27L107-R115))
* Added a return statement to ensure the error is properly returned after task completion. (`group.go`, [group.goR125-R126](diffhunk://#diff-996f64128c7fffe6cc8254ea4e1ac3c5693956f86ab5c8952e525083cf14ca27R125-R126))
* Added `TestTaskGroupMetrics` to verify the correct reporting of …
> fix(taskgroup): failed group tasks not counted

- .github/workflows/main.yml
- pool.go
This pull request includes changes to the `.github/workflows/main.yml` and `pool.go` files to enhance compatibility and improve the worker management logic. The most important changes include adding Windows OS to the CI workflow and refactoring the worker management logic to simplify the code and avoid potential deadlocks.
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L14-R14): Added `windows-latest` to the list of operating systems in the matrix strategy to ensure compatibility across more environments.
* [`pool.go`](diffhunk://#diff-5c0127b47636d901a18590597909d34f79c1e67840557675b5a981c26f7601e2L15-R17): Introduced `NUM_CPU` variable to store the number of CPUs and used it to define `MAX_TASKS_CHAN_LENGTH`.
* …
> fix(dispatcher): ensure workers exit reliably when worker count is low

- internal/assert/assert.go
- internal/dispatcher/dispatcher.go
- internal/dispatcher/dispatcher_test.go
Dispatcher may panic with `send on closed channel`  when pool is closing while new jobs are being added.
`Write` tries to send on `bufferHasElements`, which may be being closed in `Close()` at the same moment. To avoid that, I decided to never close `bufferHasElements` which may seem dirty, but should work fine since `bufferHasElements` will be removed by GC anyway.
I added test case to reproduce the issue as well.
> Fixed write to closed channel in dispatcher

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
GitHub codeql analysis action currently produces this [warning](https://github.com/alitto/pond/actions/runs/12122841115):
```
CodeQL Action v2 will be deprecated on December 5th, 2024.
Please update all occurrences of the CodeQL Action in your workflow files to v3.
```
This PR fixes this issue.
> GitHub actions: fix warning

- default_test.go
- pool_test.go
- result_test.go
- task.go
- Ensure panics thrown by tasks are wrapped correctly with `ErrPanic`.
- Include stack trace in wrapped error (inspired by https://github.com/alitto/pond/pull/94)
> fix(panics): wrap panic errors correctly and include stack trace

- README.md
- pool.go
- pool_test.go
- subpool_test.go
Add support for dynamically adjusting the maximum concurrency of the pool (number of workers) via a new method `Resize(maxWorkers int)`
> feat(pool): add support for dynamically adjusting max concurrency

- README.md
- pool.go
- pool_test.go
- result.go
- result_test.go
- subpool_test.go
This pull request provides an alternative solution to the one proposed by @korotin in his pull request https://github.com/alitto/pond/pull/104 to address a race condition that can occur on `workersWaitGroup` when tasks are submitted while the pool is stopping.
- Ensure `closed` atomic bool is toggled and checked while holding the mutex to avoid race conditions.
- Ensure `workersWaitGroup.Add()` is always called while holding the mutex to avoid race conditions.
- Improve comments on submit methods to clarify the behavior when the pool is stopped.
- Refactor `trySubmit` method to make it simpler and more clear.
- Centralize worker launch in a new method called `launchWorker`.
- Replace `subpoolSubmit` with `subpoolWorker` method.
- Decrement `workerCount` counter when the pool context is …
> fix(pool): avoid race conditions when a task is submitted while the pool is stopping

- README.md
- group.go
- pool.go
- pool_test.go
- result.go
- result_test.go
- subpool_test.go
- Add methods to submit individual tasks in a non-blocking fashion (`TrySubmit` and `TrySubmitErr`). This feature was requested in https://github.com/alitto/pond/issues/103
- Expose new `DroppedTasks` metric that reflects the number of tasks that were not executed because the queue was full. Issue reported in https://github.com/alitto/pond/issues/100
- `SubmittedTasks` metric now includes dropped tasks and it stops being updated once the pool is stopped.
> feat(pool): add non-blocking submission methods and dropped tasks metric

- pool.go
- pool_test.go
- When a pool is configured in blocking mode, it could happen that a special sequence of calls to the `Submit` method produces some of them to block indefinitely if no more tasks are ever submitted to the pool before stopping it. This PR handles these corner cases by attempting to wake up submit waiters after submitting a task and after reading up all items from the queue.
> fix(pool): prevent race condition with blocking pools

- README.md
- group.go
- group_test.go
- internal/linkedbuffer/buffer_test.go
- pool_test.go
- subpool_test.go
- Expose the underlying group context via `group.Context()`. Related discussion: https://github.com/alitto/pond/discussions/120
> feat(group): expose group context via Context() method
